# Generated by Django 5.1 on 2024-08-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='department',
            field=models.CharField(choices=[('BOD', 'Board of Directors'), ('Manager', 'Manager'), ('Help Desk', 'Help Desk'), ('Gov Official', 'Government Official')], default='Help Desk', max_length=20),
        ),
    ]
