# Generated by Django 5.1 on 2024-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='other_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='purpose',
            field=models.CharField(choices=[('Business', 'Business Meeting'), ('Support', 'Customer Support'), ('Consultation', 'Consultation'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
