# Generated by Django 5.1 on 2024-08-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_review_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='review',
        ),
    ]
